/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Coordinate = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
});
export const Aircraft = IDL.Record({
  'model' : IDL.Text,
  'manufacturer' : IDL.Text,
  'year' : IDL.Opt(IDL.Nat),
  'registrationNumber' : IDL.Text,
  'ICAOType' : IDL.Text,
  'aircraftType' : IDL.Text,
});
export const CasualtyData = IDL.Record({
  'fatalities' : IDL.Nat,
  'totalAboard' : IDL.Nat,
  'crewFatalities' : IDL.Nat,
  'survivors' : IDL.Nat,
  'passengerFatalities' : IDL.Nat,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const InvestigationEntry = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'author' : IDL.Text,
  'timestamp' : IDL.Int,
  'mediaUrls' : IDL.Vec(IDL.Text),
  'photos' : IDL.Vec(ExternalBlob),
});
export const FlightPathPoint = IDL.Record({
  'altitude' : IDL.Opt(IDL.Float64),
  'speed' : IDL.Opt(IDL.Float64),
  'coordinate' : Coordinate,
  'known' : IDL.Bool,
});
export const CrashRecord = IDL.Record({
  'id' : IDL.Nat,
  'incidentPhotos' : IDL.Vec(ExternalBlob),
  'status' : IDL.Opt(IDL.Text),
  'crashCause' : IDL.Text,
  'source' : IDL.Text,
  'flightNumber' : IDL.Text,
  'submittingOrganization' : IDL.Opt(IDL.Text),
  'casualties' : CasualtyData,
  'lastUpdated' : IDL.Int,
  'phaseOfFlight' : IDL.Text,
  'flightPath' : IDL.Vec(FlightPathPoint),
  'investigationTimeline' : IDL.Vec(InvestigationEntry),
  'aircraft' : Aircraft,
  'externalReferences' : IDL.Vec(IDL.Text),
  'airline' : IDL.Text,
  'crashDate' : IDL.Int,
  'location' : Coordinate,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addCrashRecord' : IDL.Func(
      [
        IDL.Int,
        Coordinate,
        IDL.Text,
        IDL.Text,
        Aircraft,
        IDL.Text,
        CasualtyData,
        IDL.Text,
        IDL.Text,
        IDL.Vec(InvestigationEntry),
        IDL.Vec(FlightPathPoint),
      ],
      [IDL.Nat],
      [],
    ),
  'addInvestigationEntry' : IDL.Func(
      [IDL.Nat, IDL.Int, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'attachPhotoToCrashRecord' : IDL.Func([IDL.Nat, ExternalBlob], [], []),
  'attachPhotoToEntry' : IDL.Func([IDL.Nat, IDL.Nat, ExternalBlob], [], []),
  'getAllCrashRecordsSorted' : IDL.Func([], [IDL.Vec(CrashRecord)], ['query']),
  'getAllInvestigationEntries' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(InvestigationEntry)],
      ['query'],
    ),
  'getCompleteFlightPath' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(IDL.Vec(FlightPathPoint))],
      ['query'],
    ),
  'getCrashRecord' : IDL.Func([IDL.Nat], [CrashRecord], ['query']),
  'getCrashRecordsByDateRange' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(CrashRecord)],
      ['query'],
    ),
  'getCrashRecordsByPhase' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(CrashRecord)],
      ['query'],
    ),
  'getInvestigationEntry' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Opt(InvestigationEntry)],
      ['query'],
    ),
  'getSurvivorStories' : IDL.Func([], [IDL.Vec(CrashRecord)], ['query']),
  'searchCrashRecordsByKeyword' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(CrashRecord)],
      ['query'],
    ),
  'updateCrashRecord' : IDL.Func(
      [
        IDL.Nat,
        IDL.Int,
        Coordinate,
        IDL.Text,
        IDL.Text,
        Aircraft,
        IDL.Text,
        CasualtyData,
        IDL.Text,
        IDL.Text,
        IDL.Vec(InvestigationEntry),
        IDL.Vec(FlightPathPoint),
      ],
      [],
      [],
    ),
  'updateInvestigationEntry' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Int, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Coordinate = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
  });
  const Aircraft = IDL.Record({
    'model' : IDL.Text,
    'manufacturer' : IDL.Text,
    'year' : IDL.Opt(IDL.Nat),
    'registrationNumber' : IDL.Text,
    'ICAOType' : IDL.Text,
    'aircraftType' : IDL.Text,
  });
  const CasualtyData = IDL.Record({
    'fatalities' : IDL.Nat,
    'totalAboard' : IDL.Nat,
    'crewFatalities' : IDL.Nat,
    'survivors' : IDL.Nat,
    'passengerFatalities' : IDL.Nat,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const InvestigationEntry = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'author' : IDL.Text,
    'timestamp' : IDL.Int,
    'mediaUrls' : IDL.Vec(IDL.Text),
    'photos' : IDL.Vec(ExternalBlob),
  });
  const FlightPathPoint = IDL.Record({
    'altitude' : IDL.Opt(IDL.Float64),
    'speed' : IDL.Opt(IDL.Float64),
    'coordinate' : Coordinate,
    'known' : IDL.Bool,
  });
  const CrashRecord = IDL.Record({
    'id' : IDL.Nat,
    'incidentPhotos' : IDL.Vec(ExternalBlob),
    'status' : IDL.Opt(IDL.Text),
    'crashCause' : IDL.Text,
    'source' : IDL.Text,
    'flightNumber' : IDL.Text,
    'submittingOrganization' : IDL.Opt(IDL.Text),
    'casualties' : CasualtyData,
    'lastUpdated' : IDL.Int,
    'phaseOfFlight' : IDL.Text,
    'flightPath' : IDL.Vec(FlightPathPoint),
    'investigationTimeline' : IDL.Vec(InvestigationEntry),
    'aircraft' : Aircraft,
    'externalReferences' : IDL.Vec(IDL.Text),
    'airline' : IDL.Text,
    'crashDate' : IDL.Int,
    'location' : Coordinate,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addCrashRecord' : IDL.Func(
        [
          IDL.Int,
          Coordinate,
          IDL.Text,
          IDL.Text,
          Aircraft,
          IDL.Text,
          CasualtyData,
          IDL.Text,
          IDL.Text,
          IDL.Vec(InvestigationEntry),
          IDL.Vec(FlightPathPoint),
        ],
        [IDL.Nat],
        [],
      ),
    'addInvestigationEntry' : IDL.Func(
        [IDL.Nat, IDL.Int, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'attachPhotoToCrashRecord' : IDL.Func([IDL.Nat, ExternalBlob], [], []),
    'attachPhotoToEntry' : IDL.Func([IDL.Nat, IDL.Nat, ExternalBlob], [], []),
    'getAllCrashRecordsSorted' : IDL.Func(
        [],
        [IDL.Vec(CrashRecord)],
        ['query'],
      ),
    'getAllInvestigationEntries' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(InvestigationEntry)],
        ['query'],
      ),
    'getCompleteFlightPath' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(IDL.Vec(FlightPathPoint))],
        ['query'],
      ),
    'getCrashRecord' : IDL.Func([IDL.Nat], [CrashRecord], ['query']),
    'getCrashRecordsByDateRange' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(CrashRecord)],
        ['query'],
      ),
    'getCrashRecordsByPhase' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CrashRecord)],
        ['query'],
      ),
    'getInvestigationEntry' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Opt(InvestigationEntry)],
        ['query'],
      ),
    'getSurvivorStories' : IDL.Func([], [IDL.Vec(CrashRecord)], ['query']),
    'searchCrashRecordsByKeyword' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CrashRecord)],
        ['query'],
      ),
    'updateCrashRecord' : IDL.Func(
        [
          IDL.Nat,
          IDL.Int,
          Coordinate,
          IDL.Text,
          IDL.Text,
          Aircraft,
          IDL.Text,
          CasualtyData,
          IDL.Text,
          IDL.Text,
          IDL.Vec(InvestigationEntry),
          IDL.Vec(FlightPathPoint),
        ],
        [],
        [],
      ),
    'updateInvestigationEntry' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Int, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };