/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Aircraft {
  'model' : string,
  'manufacturer' : string,
  'year' : [] | [bigint],
  'registrationNumber' : string,
  'ICAOType' : string,
  'aircraftType' : string,
}
export interface CasualtyData {
  'fatalities' : bigint,
  'totalAboard' : bigint,
  'crewFatalities' : bigint,
  'survivors' : bigint,
  'passengerFatalities' : bigint,
}
export interface Coordinate { 'latitude' : number, 'longitude' : number }
export interface CrashRecord {
  'id' : bigint,
  'incidentPhotos' : Array<ExternalBlob>,
  'status' : [] | [string],
  'crashCause' : string,
  'source' : string,
  'flightNumber' : string,
  'submittingOrganization' : [] | [string],
  'casualties' : CasualtyData,
  'lastUpdated' : bigint,
  'phaseOfFlight' : string,
  'isDisasterCrash' : boolean,
  'flightPath' : Array<FlightPathPoint>,
  'investigationTimeline' : Array<InvestigationEntry>,
  'involvedAircraft' : Array<InvolvedAircraft>,
  'aircraft' : Aircraft,
  'externalReferences' : Array<string>,
  'airline' : string,
  'crashDate' : bigint,
  'sourceVerification' : boolean,
  'location' : Coordinate,
  'verificationStatus' : VerificationStatus,
}
export type ExternalBlob = Uint8Array;
export interface FlightPathPoint {
  'altitude' : [] | [number],
  'speed' : [] | [number],
  'coordinate' : Coordinate,
  'known' : boolean,
}
export interface InvestigationEntry {
  'id' : bigint,
  'title' : string,
  'tags' : Array<string>,
  'description' : string,
  'author' : string,
  'timestamp' : bigint,
  'mediaUrls' : Array<string>,
  'photos' : Array<ExternalBlob>,
}
export interface InvolvedAircraft {
  'casualties' : CasualtyData,
  'registrationNumber' : string,
  'aircraft' : Aircraft,
  'airline' : string,
}
export type VerificationStatus = { 'verified' : null } |
  { 'unverified' : null } |
  { 'fantasy' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addCrashRecord' : ActorMethod<
    [
      bigint,
      Coordinate,
      string,
      string,
      Aircraft,
      string,
      CasualtyData,
      string,
      string,
      Array<InvestigationEntry>,
      Array<FlightPathPoint>,
      [] | [boolean],
      boolean,
      Array<InvolvedAircraft>,
    ],
    bigint
  >,
  'addInvestigationEntry' : ActorMethod<
    [bigint, bigint, string, string, Array<string>],
    bigint
  >,
  'attachPhotoToCrashRecord' : ActorMethod<[bigint, ExternalBlob], undefined>,
  'attachPhotoToEntry' : ActorMethod<[bigint, bigint, ExternalBlob], undefined>,
  'getAllCrashRecordsSorted' : ActorMethod<[], Array<CrashRecord>>,
  'getAllInvestigationEntries' : ActorMethod<
    [bigint],
    Array<InvestigationEntry>
  >,
  'getCompleteFlightPath' : ActorMethod<
    [bigint],
    [] | [Array<FlightPathPoint>]
  >,
  'getCrashRecord' : ActorMethod<[bigint], CrashRecord>,
  'getCrashRecords' : ActorMethod<
    [[] | [boolean], [] | [boolean]],
    Array<CrashRecord>
  >,
  'getCrashRecordsByDateRange' : ActorMethod<
    [bigint, bigint],
    Array<CrashRecord>
  >,
  'getCrashRecordsByPhase' : ActorMethod<[string], Array<CrashRecord>>,
  'getInvestigationEntry' : ActorMethod<
    [bigint, bigint],
    [] | [InvestigationEntry]
  >,
  'getSurvivorStories' : ActorMethod<[], Array<CrashRecord>>,
  'searchCrashRecordsByKeyword' : ActorMethod<[string], Array<CrashRecord>>,
  'updateCrashRecord' : ActorMethod<
    [
      bigint,
      bigint,
      Coordinate,
      string,
      string,
      Aircraft,
      string,
      CasualtyData,
      string,
      string,
      Array<InvestigationEntry>,
      Array<FlightPathPoint>,
      boolean,
      Array<InvolvedAircraft>,
    ],
    undefined
  >,
  'updateInvestigationEntry' : ActorMethod<
    [bigint, bigint, bigint, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];