/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CrashRecord {
    id: bigint;
    incidentPhotos: Array<ExternalBlob>;
    status?: string;
    crashCause: string;
    source: string;
    flightNumber: string;
    submittingOrganization?: string;
    casualties: CasualtyData;
    lastUpdated: bigint;
    phaseOfFlight: string;
    isDisasterCrash: boolean;
    flightPath: Array<FlightPathPoint>;
    investigationTimeline: Array<InvestigationEntry>;
    involvedAircraft: Array<InvolvedAircraft>;
    aircraft: Aircraft;
    externalReferences: Array<string>;
    airline: string;
    crashDate: bigint;
    sourceVerification: boolean;
    location: Coordinate;
    verificationStatus: VerificationStatus;
}
export interface CasualtyData {
    fatalities: bigint;
    totalAboard: bigint;
    crewFatalities: bigint;
    survivors: bigint;
    passengerFatalities: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Coordinate {
    latitude: number;
    longitude: number;
}
export interface InvolvedAircraft {
    casualties: CasualtyData;
    registrationNumber: string;
    aircraft: Aircraft;
    airline: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Aircraft {
    model: string;
    manufacturer: string;
    year?: bigint;
    registrationNumber: string;
    ICAOType: string;
    aircraftType: string;
}
export interface InvestigationEntry {
    id: bigint;
    title: string;
    tags: Array<string>;
    description: string;
    author: string;
    timestamp: bigint;
    mediaUrls: Array<string>;
    photos: Array<ExternalBlob>;
}
export interface FlightPathPoint {
    altitude?: number;
    speed?: number;
    coordinate: Coordinate;
    known: boolean;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum VerificationStatus {
    verified = "verified",
    unverified = "unverified",
    fantasy = "fantasy"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    addCrashRecord(crashDate: bigint, location: Coordinate, airline: string, flightNumber: string, aircraft: Aircraft, phaseOfFlight: string, casualties: CasualtyData, crashCause: string, source: string, investigationTimeline: Array<InvestigationEntry>, flightPath: Array<FlightPathPoint>, isFantasyData: boolean | null, isDisasterCrash: boolean, involvedAircraft: Array<InvolvedAircraft>): Promise<bigint>;
    addInvestigationEntry(crashId: bigint, timestamp: bigint, description: string, author: string, mediaUrls: Array<string>): Promise<bigint>;
    attachPhotoToCrashRecord(crashId: bigint, photo: ExternalBlob): Promise<void>;
    attachPhotoToEntry(crashId: bigint, entryId: bigint, photo: ExternalBlob): Promise<void>;
    getAllCrashRecordsSorted(): Promise<Array<CrashRecord>>;
    getAllInvestigationEntries(crashId: bigint): Promise<Array<InvestigationEntry>>;
    getCompleteFlightPath(id: bigint): Promise<Array<FlightPathPoint> | null>;
    getCrashRecord(id: bigint): Promise<CrashRecord>;
    getCrashRecords(includeFantasy: boolean | null, includeDisasterCrashes: boolean | null): Promise<Array<CrashRecord>>;
    getCrashRecordsByDateRange(startTimestamp: bigint, endTimestamp: bigint): Promise<Array<CrashRecord>>;
    getCrashRecordsByPhase(phase: string): Promise<Array<CrashRecord>>;
    getInvestigationEntry(crashId: bigint, entryId: bigint): Promise<InvestigationEntry | null>;
    getSurvivorStories(): Promise<Array<CrashRecord>>;
    searchCrashRecordsByKeyword(keyword: string): Promise<Array<CrashRecord>>;
    updateCrashRecord(id: bigint, crashDate: bigint, location: Coordinate, airline: string, flightNumber: string, aircraft: Aircraft, phaseOfFlight: string, casualties: CasualtyData, crashCause: string, source: string, investigationTimeline: Array<InvestigationEntry>, flightPath: Array<FlightPathPoint>, isDisasterCrash: boolean, involvedAircraft: Array<InvolvedAircraft>): Promise<void>;
    updateInvestigationEntry(crashId: bigint, entryId: bigint, timestamp: bigint, newTitle: string, newDescription: string): Promise<void>;
}
import type { Aircraft as _Aircraft, CasualtyData as _CasualtyData, Coordinate as _Coordinate, CrashRecord as _CrashRecord, ExternalBlob as _ExternalBlob, FlightPathPoint as _FlightPathPoint, InvestigationEntry as _InvestigationEntry, InvolvedAircraft as _InvolvedAircraft, VerificationStatus as _VerificationStatus, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addCrashRecord(arg0: bigint, arg1: Coordinate, arg2: string, arg3: string, arg4: Aircraft, arg5: string, arg6: CasualtyData, arg7: string, arg8: string, arg9: Array<InvestigationEntry>, arg10: Array<FlightPathPoint>, arg11: boolean | null, arg12: boolean, arg13: Array<InvolvedAircraft>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addCrashRecord(arg0, arg1, arg2, arg3, to_candid_Aircraft_n8(this._uploadFile, this._downloadFile, arg4), arg5, arg6, arg7, arg8, await to_candid_vec_n10(this._uploadFile, this._downloadFile, arg9), to_candid_vec_n15(this._uploadFile, this._downloadFile, arg10), to_candid_opt_n18(this._uploadFile, this._downloadFile, arg11), arg12, to_candid_vec_n19(this._uploadFile, this._downloadFile, arg13));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCrashRecord(arg0, arg1, arg2, arg3, to_candid_Aircraft_n8(this._uploadFile, this._downloadFile, arg4), arg5, arg6, arg7, arg8, await to_candid_vec_n10(this._uploadFile, this._downloadFile, arg9), to_candid_vec_n15(this._uploadFile, this._downloadFile, arg10), to_candid_opt_n18(this._uploadFile, this._downloadFile, arg11), arg12, to_candid_vec_n19(this._uploadFile, this._downloadFile, arg13));
            return result;
        }
    }
    async addInvestigationEntry(arg0: bigint, arg1: bigint, arg2: string, arg3: string, arg4: Array<string>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addInvestigationEntry(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addInvestigationEntry(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async attachPhotoToCrashRecord(arg0: bigint, arg1: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.attachPhotoToCrashRecord(arg0, await to_candid_ExternalBlob_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.attachPhotoToCrashRecord(arg0, await to_candid_ExternalBlob_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async attachPhotoToEntry(arg0: bigint, arg1: bigint, arg2: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.attachPhotoToEntry(arg0, arg1, await to_candid_ExternalBlob_n14(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.attachPhotoToEntry(arg0, arg1, await to_candid_ExternalBlob_n14(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async getAllCrashRecordsSorted(): Promise<Array<CrashRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCrashRecordsSorted();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCrashRecordsSorted();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllInvestigationEntries(arg0: bigint): Promise<Array<InvestigationEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInvestigationEntries(arg0);
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInvestigationEntries(arg0);
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCompleteFlightPath(arg0: bigint): Promise<Array<FlightPathPoint> | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompleteFlightPath(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompleteFlightPath(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCrashRecord(arg0: bigint): Promise<CrashRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.getCrashRecord(arg0);
                return from_candid_CrashRecord_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCrashRecord(arg0);
            return from_candid_CrashRecord_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCrashRecords(arg0: boolean | null, arg1: boolean | null): Promise<Array<CrashRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCrashRecords(to_candid_opt_n18(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n18(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCrashRecords(to_candid_opt_n18(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n18(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCrashRecordsByDateRange(arg0: bigint, arg1: bigint): Promise<Array<CrashRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCrashRecordsByDateRange(arg0, arg1);
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCrashRecordsByDateRange(arg0, arg1);
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCrashRecordsByPhase(arg0: string): Promise<Array<CrashRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCrashRecordsByPhase(arg0);
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCrashRecordsByPhase(arg0);
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInvestigationEntry(arg0: bigint, arg1: bigint): Promise<InvestigationEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvestigationEntry(arg0, arg1);
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvestigationEntry(arg0, arg1);
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSurvivorStories(): Promise<Array<CrashRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSurvivorStories();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSurvivorStories();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchCrashRecordsByKeyword(arg0: string): Promise<Array<CrashRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchCrashRecordsByKeyword(arg0);
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchCrashRecordsByKeyword(arg0);
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateCrashRecord(arg0: bigint, arg1: bigint, arg2: Coordinate, arg3: string, arg4: string, arg5: Aircraft, arg6: string, arg7: CasualtyData, arg8: string, arg9: string, arg10: Array<InvestigationEntry>, arg11: Array<FlightPathPoint>, arg12: boolean, arg13: Array<InvolvedAircraft>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCrashRecord(arg0, arg1, arg2, arg3, arg4, to_candid_Aircraft_n8(this._uploadFile, this._downloadFile, arg5), arg6, arg7, arg8, arg9, await to_candid_vec_n10(this._uploadFile, this._downloadFile, arg10), to_candid_vec_n15(this._uploadFile, this._downloadFile, arg11), arg12, to_candid_vec_n19(this._uploadFile, this._downloadFile, arg13));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCrashRecord(arg0, arg1, arg2, arg3, arg4, to_candid_Aircraft_n8(this._uploadFile, this._downloadFile, arg5), arg6, arg7, arg8, arg9, await to_candid_vec_n10(this._uploadFile, this._downloadFile, arg10), to_candid_vec_n15(this._uploadFile, this._downloadFile, arg11), arg12, to_candid_vec_n19(this._uploadFile, this._downloadFile, arg13));
            return result;
        }
    }
    async updateInvestigationEntry(arg0: bigint, arg1: bigint, arg2: bigint, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInvestigationEntry(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInvestigationEntry(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
}
function from_candid_Aircraft_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Aircraft): Aircraft {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
async function from_candid_CrashRecord_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CrashRecord): Promise<CrashRecord> {
    return await from_candid_record_n24(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_FlightPathPoint_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FlightPathPoint): FlightPathPoint {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
async function from_candid_InvestigationEntry_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InvestigationEntry): Promise<InvestigationEntry> {
    return await from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_InvolvedAircraft_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InvolvedAircraft): InvolvedAircraft {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_VerificationStatus_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VerificationStatus): VerificationStatus {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_FlightPathPoint>]): Array<FlightPathPoint> | null {
    return value.length === 0 ? null : from_candid_vec_n28(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_InvestigationEntry]): Promise<InvestigationEntry | null> {
    return value.length === 0 ? null : await from_candid_InvestigationEntry_n33(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    incidentPhotos: Array<_ExternalBlob>;
    status: [] | [string];
    crashCause: string;
    source: string;
    flightNumber: string;
    submittingOrganization: [] | [string];
    casualties: _CasualtyData;
    lastUpdated: bigint;
    phaseOfFlight: string;
    isDisasterCrash: boolean;
    flightPath: Array<_FlightPathPoint>;
    investigationTimeline: Array<_InvestigationEntry>;
    involvedAircraft: Array<_InvolvedAircraft>;
    aircraft: _Aircraft;
    externalReferences: Array<string>;
    airline: string;
    crashDate: bigint;
    sourceVerification: boolean;
    location: _Coordinate;
    verificationStatus: _VerificationStatus;
}): Promise<{
    id: bigint;
    incidentPhotos: Array<ExternalBlob>;
    status?: string;
    crashCause: string;
    source: string;
    flightNumber: string;
    submittingOrganization?: string;
    casualties: CasualtyData;
    lastUpdated: bigint;
    phaseOfFlight: string;
    isDisasterCrash: boolean;
    flightPath: Array<FlightPathPoint>;
    investigationTimeline: Array<InvestigationEntry>;
    involvedAircraft: Array<InvolvedAircraft>;
    aircraft: Aircraft;
    externalReferences: Array<string>;
    airline: string;
    crashDate: bigint;
    sourceVerification: boolean;
    location: Coordinate;
    verificationStatus: VerificationStatus;
}> {
    return {
        id: value.id,
        incidentPhotos: await from_candid_vec_n25(_uploadFile, _downloadFile, value.incidentPhotos),
        status: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.status)),
        crashCause: value.crashCause,
        source: value.source,
        flightNumber: value.flightNumber,
        submittingOrganization: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.submittingOrganization)),
        casualties: value.casualties,
        lastUpdated: value.lastUpdated,
        phaseOfFlight: value.phaseOfFlight,
        isDisasterCrash: value.isDisasterCrash,
        flightPath: from_candid_vec_n28(_uploadFile, _downloadFile, value.flightPath),
        investigationTimeline: await from_candid_vec_n32(_uploadFile, _downloadFile, value.investigationTimeline),
        involvedAircraft: from_candid_vec_n35(_uploadFile, _downloadFile, value.involvedAircraft),
        aircraft: from_candid_Aircraft_n38(_uploadFile, _downloadFile, value.aircraft),
        externalReferences: value.externalReferences,
        airline: value.airline,
        crashDate: value.crashDate,
        sourceVerification: value.sourceVerification,
        location: value.location,
        verificationStatus: from_candid_VerificationStatus_n40(_uploadFile, _downloadFile, value.verificationStatus)
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    altitude: [] | [number];
    speed: [] | [number];
    coordinate: _Coordinate;
    known: boolean;
}): {
    altitude?: number;
    speed?: number;
    coordinate: Coordinate;
    known: boolean;
} {
    return {
        altitude: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.altitude)),
        speed: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.speed)),
        coordinate: value.coordinate,
        known: value.known
    };
}
async function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    tags: Array<string>;
    description: string;
    author: string;
    timestamp: bigint;
    mediaUrls: Array<string>;
    photos: Array<_ExternalBlob>;
}): Promise<{
    id: bigint;
    title: string;
    tags: Array<string>;
    description: string;
    author: string;
    timestamp: bigint;
    mediaUrls: Array<string>;
    photos: Array<ExternalBlob>;
}> {
    return {
        id: value.id,
        title: value.title,
        tags: value.tags,
        description: value.description,
        author: value.author,
        timestamp: value.timestamp,
        mediaUrls: value.mediaUrls,
        photos: await from_candid_vec_n25(_uploadFile, _downloadFile, value.photos)
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    casualties: _CasualtyData;
    registrationNumber: string;
    aircraft: _Aircraft;
    airline: string;
}): {
    casualties: CasualtyData;
    registrationNumber: string;
    aircraft: Aircraft;
    airline: string;
} {
    return {
        casualties: value.casualties,
        registrationNumber: value.registrationNumber,
        aircraft: from_candid_Aircraft_n38(_uploadFile, _downloadFile, value.aircraft),
        airline: value.airline
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    model: string;
    manufacturer: string;
    year: [] | [bigint];
    registrationNumber: string;
    ICAOType: string;
    aircraftType: string;
}): {
    model: string;
    manufacturer: string;
    year?: bigint;
    registrationNumber: string;
    ICAOType: string;
    aircraftType: string;
} {
    return {
        model: value.model,
        manufacturer: value.manufacturer,
        year: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.year)),
        registrationNumber: value.registrationNumber,
        ICAOType: value.ICAOType,
        aircraftType: value.aircraftType
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    verified: null;
} | {
    unverified: null;
} | {
    fantasy: null;
}): VerificationStatus {
    return "verified" in value ? VerificationStatus.verified : "unverified" in value ? VerificationStatus.unverified : "fantasy" in value ? VerificationStatus.fantasy : value;
}
async function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CrashRecord>): Promise<Array<CrashRecord>> {
    return await Promise.all(value.map(async (x)=>await from_candid_CrashRecord_n23(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n26(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FlightPathPoint>): Array<FlightPathPoint> {
    return value.map((x)=>from_candid_FlightPathPoint_n29(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InvestigationEntry>): Promise<Array<InvestigationEntry>> {
    return await Promise.all(value.map(async (x)=>await from_candid_InvestigationEntry_n33(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InvolvedAircraft>): Array<InvolvedAircraft> {
    return value.map((x)=>from_candid_InvolvedAircraft_n36(_uploadFile, _downloadFile, x));
}
function to_candid_Aircraft_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Aircraft): _Aircraft {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_FlightPathPoint_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FlightPathPoint): _FlightPathPoint {
    return to_candid_record_n17(_uploadFile, _downloadFile, value);
}
async function to_candid_InvestigationEntry_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InvestigationEntry): Promise<_InvestigationEntry> {
    return await to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_InvolvedAircraft_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InvolvedAircraft): _InvolvedAircraft {
    return to_candid_record_n21(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: boolean | null): [] | [boolean] {
    return value === null ? candid_none() : candid_some(value);
}
async function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    tags: Array<string>;
    description: string;
    author: string;
    timestamp: bigint;
    mediaUrls: Array<string>;
    photos: Array<ExternalBlob>;
}): Promise<{
    id: bigint;
    title: string;
    tags: Array<string>;
    description: string;
    author: string;
    timestamp: bigint;
    mediaUrls: Array<string>;
    photos: Array<_ExternalBlob>;
}> {
    return {
        id: value.id,
        title: value.title,
        tags: value.tags,
        description: value.description,
        author: value.author,
        timestamp: value.timestamp,
        mediaUrls: value.mediaUrls,
        photos: await to_candid_vec_n13(_uploadFile, _downloadFile, value.photos)
    };
}
function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    altitude?: number;
    speed?: number;
    coordinate: Coordinate;
    known: boolean;
}): {
    altitude: [] | [number];
    speed: [] | [number];
    coordinate: _Coordinate;
    known: boolean;
} {
    return {
        altitude: value.altitude ? candid_some(value.altitude) : candid_none(),
        speed: value.speed ? candid_some(value.speed) : candid_none(),
        coordinate: value.coordinate,
        known: value.known
    };
}
function to_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    casualties: CasualtyData;
    registrationNumber: string;
    aircraft: Aircraft;
    airline: string;
}): {
    casualties: _CasualtyData;
    registrationNumber: string;
    aircraft: _Aircraft;
    airline: string;
} {
    return {
        casualties: value.casualties,
        registrationNumber: value.registrationNumber,
        aircraft: to_candid_Aircraft_n8(_uploadFile, _downloadFile, value.aircraft),
        airline: value.airline
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    model: string;
    manufacturer: string;
    year?: bigint;
    registrationNumber: string;
    ICAOType: string;
    aircraftType: string;
}): {
    model: string;
    manufacturer: string;
    year: [] | [bigint];
    registrationNumber: string;
    ICAOType: string;
    aircraftType: string;
} {
    return {
        model: value.model,
        manufacturer: value.manufacturer,
        year: value.year ? candid_some(value.year) : candid_none(),
        registrationNumber: value.registrationNumber,
        ICAOType: value.ICAOType,
        aircraftType: value.aircraftType
    };
}
async function to_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<InvestigationEntry>): Promise<Array<_InvestigationEntry>> {
    return await Promise.all(value.map(async (x)=>await to_candid_InvestigationEntry_n11(_uploadFile, _downloadFile, x)));
}
async function to_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n14(_uploadFile, _downloadFile, x)));
}
function to_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<FlightPathPoint>): Array<_FlightPathPoint> {
    return value.map((x)=>to_candid_FlightPathPoint_n16(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<InvolvedAircraft>): Array<_InvolvedAircraft> {
    return value.map((x)=>to_candid_InvolvedAircraft_n20(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
